package com.freightwise.software.test.dto.downstream.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class WeatherInfo {
  //Autogenerated these classes from an online service -- JSON to POJO generator.
  // Class names and properties /ought/ to be UpperCamelCase and lowerCamelCase, respectively,
  // but the online generator kept snake_case. I'm not gonna change it here for times' sake
  // but would do so in a work task
  private Location location;
  private Current current;
  private Forecast forecast;
}
